/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bearya_robot_talkypen_canjni_Canjni */

#ifndef _Included_com_bearya_actionlib_canjni_Canjni
#define _Included_com_bearya_actionlib_canjni_Canjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bearya_robot_talkypen_canjni_Canjni
 * Method:    open_can
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bearya_actionlib_canjni_Canjni_open_1can
  (JNIEnv *, jclass,jint,jint);

/*
 * Class:     com_bearya_robot_talkypen_canjni_Canjni
 * Method:    close_can
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bearya_actionlib_canjni_Canjni_close_1can
  (JNIEnv *, jclass);

/*
 * Class:     com_bearya_robot_talkypen_canjni_Canjni
 * Method:    read_can
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bearya_actionlib_canjni_Canjni_read_1can
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_bearya_robot_talkypen_canjni_Canjni
 * Method:    write_can
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bearya_actionlib_canjni_Canjni_write_1can
  (JNIEnv *, jclass, jbyteArray, jint,jint);

JNIEXPORT jint JNICALL Java_com_bearya_actionlib_canjni_Canjni_ReceiveRfData
  (JNIEnv *env, jclass thiz ,jbyteArray Rxbuf );

JNIEXPORT jint JNICALL Java_com_bearya_actionlib_canjni_Canjni_SendRfData
   (JNIEnv *env, jobject thiz,jbyteArray Txbuf ,jint length);

JNIEXPORT jint JNICALL Java_com_bearya_actionlib_canjni_Canjni_CloseRf24l01
        (JNIEnv *env, jclass thiz );

JNIEXPORT jint JNICALL Java_com_bearya_actionlib_canjni_Canjni_OpenRf24l01
        (JNIEnv *env, jclass thiz );

#ifdef __cplusplus
}
#endif
#endif
