/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bearya_robot_talkypen_JniHelper */

#ifndef _Included_com_bearya_robot_talkypen_JniHelper
#define _Included_com_bearya_robot_talkypen_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bearya_robot_talkypen_canjni_JniHelper
 * Method:    read
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bearya_robot_talkypen_canjni_JniHelper_read
  (JNIEnv *env, jclass jobj){
        return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");
  }

#ifdef __cplusplus
}
#endif
#endif
